import { Inter } from "next/font/google";
import "./globals.css";

import "./mainStyle.css"
import "./normalize.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gaming Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <!--! google fonts Cairo  --> */}
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&display=swap" rel="stylesheet"/>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
